### ISSUE TITLE
Non support for OSX Leopard (10.5)

### ISSUE THREAD

**Issue by ramosian-glider** [ramosian-glider/sanitizers#85]
Originally reported on Google Code with ID 84

```
What steps will reproduce the problem?

1. I know from the description page that address sanitizer is supported on 10.6 (Snow
Leopard) and as I saw the build options on the Chromium project I tried on one of my
Leopard system but I can't get it work.
I get at launch : 

dyld: Symbol not found: _dispatch_after_f
  Referenced from: /tmp/./a.out
  Expected in: dynamic lookup

So I assume it doesn't work on Leopard and maybe it should be written somewhere or
the build should fail if the system is too old.

If it should work what am I doing wrong ?
```

Reported by `mkvtoolnix.build.jonthn` on 2012-06-28 15:30:27

**Comment by ramosian-glider** [comment]
```
ASan never worked on Mac OS 10.5 and we're not going to fix that, because both Apple
and Chromium are dropping the support for Leopard very soon.

You can possibly hack the source to make ASan work on Leopard (you'll have to remove
the interceptors for libdispatch functions which do not exist on Leopard, and probably
skip a couple of steps when intercepting the allocator in asan_malloc_mac.cc). I'm
not aware of any issues that may arise on Leopard, but they are certainly possible.
```

Reported by `ramosian.glider` on 2012-06-28 15:37:18
- **Status changed**: `WontFix`
- **Labels added**: OpSys-OSX

**Comment by ramosian-glider** [comment]
```
Adding Project:AddressSanitizer as part of GitHub migration.
```

Reported by `ramosian.glider` on 2015-07-30 09:12:59
- **Labels added**: ProjectAddressSanitizer
